# Generated by Django 4.0.3 on 2022-05-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='womenproduct',
            name='category',
        ),
    ]
